spring:
  datasource:
    driver-class-name: ${AECP_DB_DRIVER:com.p6spy.engine.spy.P6SpyDriver}
    url: ${AECP_DB_URL}
    username: ${AECP_DB_USERNAME}
    password: ${AECP_DB_PASSWORD}
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: ${AECP_REDIS_ADDRESS:redis://localhost:6379}
          timeout: ${AECP_REDIS_TIMEOUT:3000}
sa-token:
  alone-redis:
    database: ${AECP_REDIS_DATABASE:11}
    host: ${AECP_REDIS_HOST:127.0.0.1}
    port: ${AECP_REDIS_PORT:6379}

#文件上传
#dromara:
#  x-file-storage:
#    default-platform: tencent-cos-1
#    tencent-cos:
#      - platform: tencent-cos-1
#        enable-storage: true
#        secret-id: xxx
#        secret-key: xxxx
#        region: ap-chengdu
#        bucket-name: xxx
#        domain: xxx
#        base-path: upload/

